services:
  proxy:
    restart: unless-stopped

  api:
    restart: unless-stopped

  client:
    restart: unless-stopped
    environment:
      - NODE_ENV=production

  db:
    restart: unless-stopped
