services:
  proxy:
    build: ./proxy
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - /data
      - /config
      - ./proxy/Caddyfile:/etc/caddy/Caddyfile

  api:
    build: ./api
    environment:
      - DATABASE_URL=postgresql://postgres:123@db:5432/postgres

  client:
    build: ./client

  db:
    image: postgres:15.1-alpine
    ports:
      - 5432
    volumes:
      - /var/lib/postgresql/data
      - ./db/postgres.conf:/etc/postgres.conf
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=123
    command: |
      postgres -c config_file=/etc/postgres.conf
