import "./global.css";

import type { Metadata } from "next";
import { ReactNode } from "react";
import { Layout } from "~/components/Layout";
import { Providers } from "./providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Layout>
          <nav>
            <h1>
              <a href="">Workoelho</a>
            </h1>
            <ul>
              <li>
                <a href="/sign-in">Sign In</a>
              </li>
              <li>
                <a href="/sign-up">Sign Up</a>
              </li>
            </ul>
          </nav>

          <Providers>{children}</Providers>
        </Layout>
      </body>
    </html>
  );
}
